---
swagger: "2.0"
info:
  description: "test"
  version: "1.0.0"
  title: "rule-manager"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
host: "0.0.0.0:8081"
basePath: "/v1/src"
tags:
  - name: "alive"
    description: "Keepalive"
schemes:
  - "http"
produces:
  - "application/json"
consumes:
  - "application/json"
paths:
  /ping:
    get:
      tags:
        - "alive"
      summary: "Api keepalive"
      description: "Api keepalive"
      operationId: "is_alive"
      parameters: []
      responses:
        200:
          description: "is alive"
      x-swagger-router-controller: "controllers.rule_controller"